<?php

class Order_Service_Itemstate
{
	const ORDER_ITEM_STATE_NEW = 1;
	const ORDER_ITEM_STATE_RELEASE = 7;
	const ORDER_ITEM_STATE_DENY = 8;
	const ORDER_ITEM_STATE_RELEASED = 3;
	const ORDER_ITEM_STATE_PRODUCTION = 4;
	const ORDER_ITEM_STATE_DELIVERY = 5;
	const ORDER_ITEM_STATE_FINISHED = 6;
	const ORDER_ITEM_STATE_CORRECTION = 9;
	
}

