ALTER TABLE `rest`.`order_item` CHANGE COLUMN `locked_render` `locked_render_preview_front` TINYINT(1) NULL DEFAULT 0  , ADD COLUMN `locked_render_preview_back` TINYINT(1) NULL DEFAULT 0  AFTER `locked_render_preview_front` , ADD COLUMN `locked_render_print_front` TINYINT(1) NULL DEFAULT 0  AFTER `locked_render_preview_back` , ADD COLUMN `locked_render_print_back` TINYINT(1) NULL DEFAULT 0  AFTER `locked_render_print_front` , ADD COLUMN `locked_render_test_front` TINYINT(1) NULL DEFAULT 0  AFTER `locked_render_print_back` , ADD COLUMN `locked_render_test_back` TINYINT(1) NULL DEFAULT 0  AFTER `locked_render_test_front` ;

ALTER TABLE `rest`.`product_layout` ADD COLUMN `xsl_front_test` VARCHAR(255) NULL  AFTER `plugin_classes` , ADD COLUMN `pdf_front_test` VARCHAR(255) NULL  AFTER `xsl_front_test` , ADD COLUMN `xsl_back_test` VARCHAR(255) NULL  AFTER `pdf_front_test` , ADD COLUMN `pdf_back_test` VARCHAR(255) NULL  AFTER `xsl_back_test` ;

ALTER TABLE `rest`.`order_item` CHANGE COLUMN `locked_render_preview_front` `locked_render_front_preview` TINYINT(1) NULL DEFAULT '0'  , CHANGE COLUMN `locked_render_preview_back` `locked_render_back_preview` TINYINT(1) NULL DEFAULT '0'  , CHANGE COLUMN `locked_render_print_front` `locked_render_front_print` TINYINT(1) NULL DEFAULT '0'  , CHANGE COLUMN `locked_render_print_back` `locked_render_back_print` TINYINT(1) NULL DEFAULT '0'  , CHANGE COLUMN `locked_render_test_front` `locked_render_front_test` TINYINT(1) NULL DEFAULT '0'  , CHANGE COLUMN `locked_render_test_back` `locked_render_back_test` TINYINT(1) NULL DEFAULT '0'  ;







ALTER TABLE `rest`.`report_report` CHANGE COLUMN `title` `title` VARCHAR(45) NULL  , ADD COLUMN `xmlgrouping` VARCHAR(255) NULL DEFAULT NULL  AFTER `execsql` , ADD COLUMN `xslfile` VARCHAR(255) NULL DEFAULT NULL  AFTER `xmlgrouping` ;
UPDATE `rest`.`report_filter` SET `title`='PartnerNr', `key`='partner_nr', `jsonparam`='{\"fieldLabel\":\"PartnerNr\",\"name\":\"partner_nr\",\"format\":\"#\"}' WHERE `id`='12';
INSERT INTO `rest`.`report_filter` (`title`, `key`, `report_filtertype_id`, `report_filteroperator_id`, `report_report_id`, `jsonparam`) VALUES ('Import-Stack', 'import_stack_id', '4', '1', '7', '{\"fieldLabel\":\"Import Stapel\",\"name\":\"import_stack_id\",\"displayField\":\"title\",\"valueField\":\"id\",\"store\":\"ImportStackJsonStore\"}');
UPDATE `rest`.`report_report` SET `sql`='SET @row=0;SELECT (@row=@row+1) `lfdnr`,partner_partner.partner_nr,  partner_partner.title partner_title,   partner_address.post_anrede,  partner_address.post_name1,  partner_address.post_name2,  partner_address.post_strasse,  partner_address.post_plz,  partner_address.post_ort,   order_order.order_no_external,  DATE_FORMAT(order_order.incoming,\'%d.%m.%Y\') order_incoming_date,  order_item.product_item_no,  product_product.title AS product_title,  product_item.title AS product_item_title,  order_item.amount,  GROUP_CONCAT(product_barcode.barcode) barcodes, COALESCE(GROUP_CONCAT(product_barcode.barcode_banderole_text), (SELECT GROUP_CONCAT(value) FROM order_item_has_order_meta WHERE order_item_id = order_item.id AND order_meta_key = \"barcode_banderole\")) banderole, order_order.comment \nFROM order_pool\n  INNER JOIN order_order ON order_order.order_pool_id = order_pool.id\n  INNER JOIN order_item ON order_pool.id = order_item.order_pool_id\n  INNER JOIN product_item ON product_item.id = order_item.product_item_id\n  INNER JOIN product_product ON product_product.id = product_item.product_product_id\n  INNER JOIN partner_partner ON order_order.partner_partner_id = partner_partner.id AND partner_partner.partner_nr = {param.partner_nr}  \n  INNER JOIN partner_address ON partner_partner.partner_address_id_delivery = partner_address.id\n  LEFT JOIN product_barcode ON product_barcode.order_item_id = order_item.id\n\n  WHERE\n         order_pool.import_stack_id = {param.import_stack_id}  \n  GROUP BY order_item.id;' WHERE `id`='7';
