Sehr geehrte Kundin, sehr geehrter Kunde,

im Auftrag der Fleurop AG senden wir Ihnen die Druckfreigabe
für die von Ihnen bestellten individualisierten Werbemittel.

<?=$this->comment ?>

Im Anhang finden Sie die Druckvorschau für den Artikel
<?=$this->order_item->getProductProduct()->title ?>, <?=$this->order_item->getProductItem()->title ?>.

Um die Druckvorschau für den Druck freizugeben, klicken Sie bitte auf folgenden Link:
<?=Zend_Registry::get('config')->external->host ?>/order/item/released?authKey=<?=$this->order_item->authkey ?>


Wenn Sie eine Korrektur wünschen, klicken Sie bitte auf diesen Link:
<?=Zend_Registry::get('config')->external->host ?>/order/item/correction?authKey=<?=$this->order_item->authkey ?>


Mit freundlichen Grüßen,

Ihr Team von Mundschenk Druck+Medien