Sehr geehrte Kundin, sehr geehrter Kunde,

im Anhang finden Sie die Ihre Druckvorschau.

Um die Druckvorschau für den Druck freizugeben, klicken Sie bitte auf folgenden Link:
<?=Zend_Registry::get('config')->external->host ?>/order/item/released?authKey=<?=$this->order_item->authkey ?>


Wenn Sie eine Korrektur wünschen, klicken Sie bitte auf diesen Link:
<?=Zend_Registry::get('config')->external->host ?>/order/item/correction?authKey=<?=$this->order_item->authkey ?>


Mit freundlichen Grüßen,

Ihr Team von der Druckerei Mundschenk